### ISSUE TITLE
Lab 17 review

### ISSUE THREAD

**Issue by Erhil** [mipt-cs/course-advanced_python#1]
Отревьюить 17 лабу.

Erhil
- [ ] Лаба корректно отображается
- [ ] Материал понятный
- [ ] Присутствует не менее 3 задач
- [ ] Орфография и пунктуация ок
- [ ] Код корректно оформлен

gemial
- [x] Лаба корректно отображается
- [x] Материал понятный
- [x] Присутствует не менее 3 задач
- [x] Орфография и пунктуация ок
- [x] Код корректно оформлен

**Comment by gemial** [comment]
Добавить UPDATE и DELETE запросы в таблицу.
